//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DataAccess.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_COMPLEJOSEntities : DbContext
    {
        public BD_COMPLEJOSEntities()
            : base("name=BD_COMPLEJOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<usuario> usuario { get; set; }
    
        public virtual ObjectResult<SP_MOD_EQUIPO_CREACION_Result> SP_MOD_EQUIPO_CREACION(string id_usuario, string nombre_equipo, Nullable<bool> estado)
        {
            var id_usuarioParameter = id_usuario != null ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(string));
    
            var nombre_equipoParameter = nombre_equipo != null ?
                new ObjectParameter("nombre_equipo", nombre_equipo) :
                new ObjectParameter("nombre_equipo", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MOD_EQUIPO_CREACION_Result>("SP_MOD_EQUIPO_CREACION", id_usuarioParameter, nombre_equipoParameter, estadoParameter);
        }
    
        public virtual ObjectResult<SP_MOD_EQUIPO_ELIMINACION_Result> SP_MOD_EQUIPO_ELIMINACION(string id_usuario, Nullable<int> id_equipo)
        {
            var id_usuarioParameter = id_usuario != null ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(string));
    
            var id_equipoParameter = id_equipo.HasValue ?
                new ObjectParameter("id_equipo", id_equipo) :
                new ObjectParameter("id_equipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MOD_EQUIPO_ELIMINACION_Result>("SP_MOD_EQUIPO_ELIMINACION", id_usuarioParameter, id_equipoParameter);
        }
    
        public virtual ObjectResult<SP_MOD_EQUIPO_LISTADO_Result> SP_MOD_EQUIPO_LISTADO(string id_usuario, string nombre_equipo)
        {
            var id_usuarioParameter = id_usuario != null ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(string));
    
            var nombre_equipoParameter = nombre_equipo != null ?
                new ObjectParameter("nombre_equipo", nombre_equipo) :
                new ObjectParameter("nombre_equipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MOD_EQUIPO_LISTADO_Result>("SP_MOD_EQUIPO_LISTADO", id_usuarioParameter, nombre_equipoParameter);
        }
    
        public virtual ObjectResult<SP_MOD_EQUIPO_MODIFICACION_Result> SP_MOD_EQUIPO_MODIFICACION(string id_usuario, Nullable<int> id_equipo, string nombre_equipo, Nullable<bool> estado)
        {
            var id_usuarioParameter = id_usuario != null ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(string));
    
            var id_equipoParameter = id_equipo.HasValue ?
                new ObjectParameter("id_equipo", id_equipo) :
                new ObjectParameter("id_equipo", typeof(int));
    
            var nombre_equipoParameter = nombre_equipo != null ?
                new ObjectParameter("nombre_equipo", nombre_equipo) :
                new ObjectParameter("nombre_equipo", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MOD_EQUIPO_MODIFICACION_Result>("SP_MOD_EQUIPO_MODIFICACION", id_usuarioParameter, id_equipoParameter, nombre_equipoParameter, estadoParameter);
        }
    
        public virtual ObjectResult<SP_MOD_SEDE_CREACION_Result> SP_MOD_SEDE_CREACION(string id_usuario, string nombre_sede, Nullable<int> num_complejo, Nullable<decimal> presupuesto, Nullable<bool> estado)
        {
            var id_usuarioParameter = id_usuario != null ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(string));
    
            var nombre_sedeParameter = nombre_sede != null ?
                new ObjectParameter("nombre_sede", nombre_sede) :
                new ObjectParameter("nombre_sede", typeof(string));
    
            var num_complejoParameter = num_complejo.HasValue ?
                new ObjectParameter("num_complejo", num_complejo) :
                new ObjectParameter("num_complejo", typeof(int));
    
            var presupuestoParameter = presupuesto.HasValue ?
                new ObjectParameter("presupuesto", presupuesto) :
                new ObjectParameter("presupuesto", typeof(decimal));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MOD_SEDE_CREACION_Result>("SP_MOD_SEDE_CREACION", id_usuarioParameter, nombre_sedeParameter, num_complejoParameter, presupuestoParameter, estadoParameter);
        }
    
        public virtual ObjectResult<SP_MOD_SEDE_ELIMINACION_Result> SP_MOD_SEDE_ELIMINACION(string id_usuario, Nullable<int> id_sede)
        {
            var id_usuarioParameter = id_usuario != null ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(string));
    
            var id_sedeParameter = id_sede.HasValue ?
                new ObjectParameter("id_sede", id_sede) :
                new ObjectParameter("id_sede", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MOD_SEDE_ELIMINACION_Result>("SP_MOD_SEDE_ELIMINACION", id_usuarioParameter, id_sedeParameter);
        }
    
        public virtual ObjectResult<SP_MOD_SEDE_LISTADO_Result> SP_MOD_SEDE_LISTADO(string id_usuario, string nombre_sede)
        {
            var id_usuarioParameter = id_usuario != null ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(string));
    
            var nombre_sedeParameter = nombre_sede != null ?
                new ObjectParameter("nombre_sede", nombre_sede) :
                new ObjectParameter("nombre_sede", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MOD_SEDE_LISTADO_Result>("SP_MOD_SEDE_LISTADO", id_usuarioParameter, nombre_sedeParameter);
        }
    
        public virtual ObjectResult<SP_MOD_SEDE_MODIFICACION_Result> SP_MOD_SEDE_MODIFICACION(string id_usuario, Nullable<int> id_sede, string nombre_sede, Nullable<int> num_complejo, Nullable<decimal> presupuesto, Nullable<bool> estado)
        {
            var id_usuarioParameter = id_usuario != null ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(string));
    
            var id_sedeParameter = id_sede.HasValue ?
                new ObjectParameter("id_sede", id_sede) :
                new ObjectParameter("id_sede", typeof(int));
    
            var nombre_sedeParameter = nombre_sede != null ?
                new ObjectParameter("nombre_sede", nombre_sede) :
                new ObjectParameter("nombre_sede", typeof(string));
    
            var num_complejoParameter = num_complejo.HasValue ?
                new ObjectParameter("num_complejo", num_complejo) :
                new ObjectParameter("num_complejo", typeof(int));
    
            var presupuestoParameter = presupuesto.HasValue ?
                new ObjectParameter("presupuesto", presupuesto) :
                new ObjectParameter("presupuesto", typeof(decimal));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MOD_SEDE_MODIFICACION_Result>("SP_MOD_SEDE_MODIFICACION", id_usuarioParameter, id_sedeParameter, nombre_sedeParameter, num_complejoParameter, presupuestoParameter, estadoParameter);
        }
    
        public virtual ObjectResult<SP_MOD_EQUIPO_DETALLE_Result> SP_MOD_EQUIPO_DETALLE(string id_usuario, Nullable<int> id_equipo)
        {
            var id_usuarioParameter = id_usuario != null ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(string));
    
            var id_equipoParameter = id_equipo.HasValue ?
                new ObjectParameter("id_equipo", id_equipo) :
                new ObjectParameter("id_equipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MOD_EQUIPO_DETALLE_Result>("SP_MOD_EQUIPO_DETALLE", id_usuarioParameter, id_equipoParameter);
        }
    
        public virtual ObjectResult<SP_MOD_SEDE_DETALLE_Result> SP_MOD_SEDE_DETALLE(string id_usuario, Nullable<int> id_sede)
        {
            var id_usuarioParameter = id_usuario != null ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(string));
    
            var id_sedeParameter = id_sede.HasValue ?
                new ObjectParameter("id_sede", id_sede) :
                new ObjectParameter("id_sede", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MOD_SEDE_DETALLE_Result>("SP_MOD_SEDE_DETALLE", id_usuarioParameter, id_sedeParameter);
        }
    }
}
